language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- ./run_tests.sh
deploy:
  provider: s3
  access_key_id: AKIAJ2CEZVTSFRBCKRJQ
  secret_access_key:
    secure: og3FLG+lq3d00+sYGRRh0xfqAO4KaPR8zOR9QRQY1z5HjR8AbwAvwJMLQRC7LX6Fc+Md+lkDWgt6plZ830jO1PwVQovaEKtW2c1gzlSqw+xqA2ZEvkDgyMf2Lsi6C6RJHBVmqc0BH3NYjT2Q2cPzWvCrKbnkinLHmGIhKDhqnd/9HH+gbpCTL4tjzoy3UxZYvGGuI1EsRMddJa8vKowa3fh9dt6V7xTM6gx5bAfqWaZ655DqiAMwaI2SaLxkW2OCRM0sxNXQjmDX8t2NaK9srzH4fGWn2aZWIp6MsGb7r0VpxUA4gMGYpSE4oBShs5+3sSPffte/sf4a2BfzY+n0XGE5kRbqCDYF/w7q9ffyEtUW6trCFD2lCkdnWXVslC04uNYQxeUv4jT2iRDqVntoWlC5fuiYIVJ0s+Wv4nMJB5shuKCG5zeWrpw+D39TvaOwJ2YN/cNJ/aBQFQBMyrYu2xkdG3kE2aAJa2SOMKXVzVjPRpxERSWtZxpMTwVDCJsXuYysvVrBAeTpJJ6kY7dauBMvCX+EbA8HaOayRRP42H3Ldvtnf277lhYOMPCh8+81FovEMFvgFjR/dtcgE/qdTAlDvwt2JZ3iCwLHNBros7P5xL0ZXLpU5b/0HB6hdyON4w+splKcqhnHzRcihfRG0eIx8kbrKj1M/radx6sYIS8=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: acctdictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/ACCOuNT_dictionary
    all_branches: true
